<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.susongyan</groupId>
    <artifactId>bobapop-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>bobapop</name>

    <modules>
        <module>bobapop-core</module>
        <module>bobapop-spring-data-redis</module>
        <module>bobapop-jedis-legacy</module>
        <module>bobapop-jedis-modern</module>
        <module>bobapop-lettuce</module>
        <module>demo/boot1</module>
        <module>demo/boot2</module>
        <module>demo/boot3</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>8</maven.compiler.release>
        <spring-data-redis.baseline.version>1.8.23.RELEASE</spring-data-redis.baseline.version>
        <jedis-legacy.baseline.version>2.9.0</jedis-legacy.baseline.version>
        <jedis-modern.baseline.version>4.4.8</jedis-modern.baseline.version>
        <lettuce.baseline.version>5.3.7.RELEASE</lettuce.baseline.version>
        <junit.version>4.13.2</junit.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.susongyan</groupId>
                <artifactId>bobapop-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.susongyan</groupId>
                <artifactId>bobapop-spring-data-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.susongyan</groupId>
                <artifactId>bobapop-jedis-legacy</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.susongyan</groupId>
                <artifactId>bobapop-jedis-modern</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.susongyan</groupId>
                <artifactId>bobapop-lettuce</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
